---
- name: Deploy CloudOptima Application
  hosts: app
  become: true

  vars:
    app_name: "demo-payment-api-2"
    app_port: 80
    container_port: 8080

    aws_region: "eu-north-1"
    ecr_registry: "411902101270.dkr.ecr.eu-north-1.amazonaws.com"
    ecr_repository: "cloudoptima/demo-payment-api-2"

    # Jenkins will provide this.
    image_tag: "latest"

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - awscli
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Authenticate Docker to Amazon ECR
      ansible.builtin.shell: |
        aws ecr get-login-password --region {{ aws_region }} |
        docker login \
          --username AWS \
          --password-stdin \
          {{ ecr_registry }}
      args:
        executable: /bin/bash
      no_log: true

    - name: Pull application image from ECR
      community.docker.docker_image:
        name: "{{ ecr_registry }}/{{ ecr_repository }}:{{ image_tag }}"
        source: pull

    - name: Stop old application container
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent

    - name: Run application container
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ ecr_registry }}/{{ ecr_repository }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ app_port }}:{{ container_port }}"

    - name: Run Prometheus Node Exporter
      community.docker.docker_container:
        name: "node-exporter"
        image: "prom/node-exporter:latest"
        state: started
        restart_policy: always
        published_ports:
          - "9100:9100"
